#!/bin/bash

help() {
  echo "Usage:"
  echo "  action create [name]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro template create action "$@"
}

run() {
  core "$@"
}

run "$@"
