#!/bin/bash

help() {
  echo "Usage:"
  echo "  zaction download <action>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local name=$1
  if [ -z "$name" ]; then
    log::error "action name is requried"
    exit 1
  fi

  # @TODO
  local version=""
  if [ "$2" = "-v" ]; then
    version=$3
  fi

  action::clone $name $version
}

run() {
  core $@
}

run $@
